---
title: "Stat 240 Final Project - Diya, Max, Cindy, Peian"
output: html_document
date: "2025-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE,
                      warning = FALSE, error = FALSE,
                      fig.height = 3)
library(tidyverse)
```


```{r}
population =  read_csv("C:/Users/yefim/OneDrive/Desktop/STAT240/project/population.csv")
gdp = read_csv("C:/Users/yefim/OneDrive/Desktop/STAT240/project/gdp.csv")

combined = left_join(population, gdp, by = c("Country Name", "Year")) %>% 
  filter(Year >= 2000 & Year < 2020)

combined = combined[, -2]
combined = combined[, -4]

combined = combined %>% 
  rename(Population = Value.x, GDP = Value.y) %>% 
  mutate(GDP_per_capita = GDP / Population) %>% 
  rename(`GDP Per Capita` = GDP_per_capita)

population
gdp
combined
```
```{r}
averages = combined %>% 
  group_by(`Country Name`) %>% 
  
  mutate(
    pop_growth = (Population - lag(Population)) / lag(Population) * 100
  ) %>%
  
  
  summarize(
    avg_population_growth = mean(pop_growth, na.rm = TRUE),
    avg_gdp_pc = mean(`GDP Per Capita`, na.rm = TRUE)
  )

averages = averages %>% 
  rename(`Average Population Growth` = avg_population_growth, `Average GDP per Capita` = avg_gdp_pc)

country_names = c(
  "Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "British Virgin Islands", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Cayman Islands", "Central African Republic", "Chad", "Channel Islands", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.", "Congo, Rep.", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Curacao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt, Arab Rep.", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Faroe Islands", "Fiji", "Finland", "France", "French Polynesia", "Gabon", "Gambia, The", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Rep.", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Dem. People's Rep.", "Korea, Rep.", "Kosovo", "Kuwait", "Kyrgyz Republic", "Lao PDR", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia, Fed. Sts.", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten (Dutch part)", "Slovak Republic", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia", "St. Martin (French part)", "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland", "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkiye", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela, RB", "Viet Nam", "Virgin Islands (U.S.)", "West Bank and Gaza", "Yemen, Rep.", "Zambia", "Zimbabwe"
)



final = averages %>% 
    filter(`Country Name` %in% country_names)

final

```


```{r}
final_graph = ggplot(final, aes(`Average GDP per Capita`, `Average Population Growth`))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, color = "pink") + # straight regression line
  labs(title = "Linear Regression by Country",
       x = "Average GDP per Capita",
       y = "Average Population Growth") +
  theme_minimal()

final_graph
```

